accounts/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url
from django.contrib.auth import views as auth_views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("login/", auth_views.LoginView.as_view(template_name="login.html"), name="login"),

]

productfinder/urls.py
from django.contrib import admin
from django.urls import path, include
from productfinder import views
from productfinder.settings import LOGIN_REDIRECT_URL, LOGOUT_REDIRECT_URL
from django.conf import settings
from django.conf.urls.static import static
from productfinder.views import api_root


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api-auth/', views.api_root),
    path('', views.ProductListView.as_view(), name="product_home"),
    path('home/', views.ProductListView.as_view(), name=LOGIN_REDIRECT_URL),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('products/', include('products.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path, include, re_path
from rest_framework.urlpatterns import format_suffix_patterns
from products import views
from products import api_views
from django.conf.urls import url

app_name = "products"
urlpatterns = [
    path('product-api/', api_views.ProductListAPI.as_view(), name="productlist_api"),
    path('product-api/<int:pk>', api_views.ProductDetailAPI.as_view(), name='productdetail_api'),
    path('user-api/', api_views.UserListAPI.as_view(), name="userlist_api"),
    path('user-api/<int:pk>', api_views.UserDetailAPI.as_view(), name="userdetail_api"),
    path('api-auth/', api_views.api_root),
    path('', api_views.api_root),
    path('new/', views.ProductCreateView.as_view(), name="new"),
    path('<int:product_id>/', views.upvote, name='upvote'),
    re_path(r'(?P<pk>\d+)$', views.ProductDetailView.as_view(), name='product_detail'),
    path('', views.ProductListView.as_view(), name="product_list"),
]


urlpatterns = format_suffix_patterns(urlpatterns)

accounts/models.py
from django.contrib import auth
from django.db import models
from django.utils import timezone

# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

products/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

User = get_user_model()


# Create your models here.
class Product(models.Model):
    title = models.CharField(max_length=50)
    published_date = models.DateTimeField(blank=True, null=True, auto_now=True)
    body = models.TextField(blank=True, default='')
    url = models.TextField(blank=True, default='')
    image = models.ImageField(upload_to="images/")
    votes_total = models.IntegerField(default=1)
    icon = models.ImageField(upload_to="images/")
    user = models.ForeignKey(User, related_name="products", on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('product_home')

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:100]

    def pretty_date(self):
        return self.published_date.strftime('%b %e %Y')

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email")
        model = get_user_model()


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth
from django.views.generic import TemplateView, CreateView
from accounts import forms
from django.urls import reverse_lazy


class SignUp(CreateView):
    form_class = forms.UserCreateForm
    template_name = "signup.html"
    success_url = reverse_lazy('product_home')

productfinder/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from products.models import Product

from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.reverse import reverse

class ProductListView(ListView):
    context_object_name = "product_list"
    model = Product

@api_view(['GET'])
def api_root(request, format=None):
    return Response({
        'products': reverse('product_home', request=request, format=format)
    })

products/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import(LoginRequiredMixin,PermissionRequiredMixin)
from django.views.generic import TemplateView, CreateView, ListView, DeleteView, UpdateView, DetailView
from products.models import Product
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

# Create your views here.
class ProductCreateView(LoginRequiredMixin, CreateView):
    fields = ("title", "body", "url", "image", "icon")
    model = Product

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class ProductListView(ListView):
    context_object_name = "product_list"
    model = Product

    def get_queryset(self):
        return Product.objects.all().order_by('-votes_total')


class ProductDetailView(DetailView):
    context_object_name = "product_detail"
    model = Product

# @login_required
def upvote(request, product_id):
    if request.method == 'POST':
        product = get_object_or_404(Product, pk=product_id)
        product.votes_total += 1
        product.save()
        return redirect('/products/' + str(product.id))

accounts/templates/login.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
  <div class="container">
      <h1>Login</h1>
      <form method="POST">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Login" class="btn btn-default">
      </form>
  </div>
{% endblock %}

accounts/templates/signup.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
  <div class="container">
      <h1>Sign Up</h1>
      <form method="POST" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Sign Up" class="btn btn-default">
      </form>
    </div>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}


{% block content %}
    <div class="row">
    <div class="col-2">
      <img src="{{ product_detail.icon.url }}" class="img-fluid" />
    </div>
    <div class="col-10">
      <a href="{{ product.url }}"><h1>{{ product_detail.title }}</h1></a>
    </div>
    </div>

    <div class="row">
    <div class="col-8">
      <img src="{{ product_detail.image.url }}" class="img-fluid" />
    </div>
    <div class="col-4">
      <a href="javascript:{document.getElementById('upvote').submit()}"><button class="btn btn-primary btn-lg btn-block"><span class="oi oi-caret-top"></span> Upvote {{ product_detail.votes_total }}</button></a>
    </div>
    </div>

    <div class="row pt-2">
    <div class="col-4">
      <h4><span class="oi oi-magnifying-glass"></span> Hunted by {{ product_detail.user.username }}</h4>
    </div>
    <div class="col-4 text-right">
      <h4><span class="oi oi-clock"></span> {{ product_detail.pretty_date }}</h4>
    </div>
    </div>

    <div class="row">
    <div class="col-8">
      <p>{{ product_detail.body }}</p>
    </div>
    </div>

    <form id="upvote" method="POST" action="{% url 'products:upvote' product_detail.id %}">
      {% csrf_token%}
      <input type="hidden">
    </form>
{% endblock %}

products/templates/products/product_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
  <div class="container">
      <h1>Create a Product</h1>
      <form action="{% url 'products:new' %}" method="POST" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Submit" class="btn btn-large">
      </form>
    </div>
{% endblock %}

products/templates/products/product_list.html
{% extends "base.html" %}

{% block content %}
  {% for product in product_list %}
    <div class="row pt-3">
      <div class="col-2" onclick="window.location='{% url 'products:product_detail' pk=product.pk %}';" style="cursor: pointer;">
        <img src="{{ product.icon.url }}" class="img-fluid" />
      </div>
      <div class="col-6" onclick="window.location='{% url 'products:product_detail' pk=product.pk %}';" style="cursor: pointer;">
        <h1>{{ product.title }}</h1>
        <p>{{ product.summary }}</p>
      </div>
      <div class="col-4">
        <a href="javascript:{document.getElementById('upvote{{ product.id }}').submit()}"><button class="btn btn-primary btn-lg btn-block"><span class="oi oi-caret-top"></span> Upvote {{ product.votes_total }}</button></a>
      </div>
    </div>
    <form id="upvote{{ product.id }}" method="POST" action="{% url 'products:upvote' product.id %}">
      {% csrf_token%}
      <input type="hidden">
    </form>
  {% endfor %}
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
  {% load fontawesome %}
  {% fontawesome_stylesheet %}
  {% load staticfiles %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">


  <title>Product Finder</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>

<body>

  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
      <a class="navbar-brand" href="{% url 'product_home' %}">
      <img src="{% static 'images/logo1.png' %}" height=50 width=50 class="d-inline-block alighn-top" />
      Product Finder
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'products:new' %}">{% fontawesome_icon 'plus-square' large=True fixed=True %}</a>
            <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Log Out</a>
          {% else %}
            <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a>
            <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
          {% endif %}
        </div>
      </div>
      </div>
    </nav>
  </header>

  <div class="container">
    {% block content %}

    {% endblock %}
  </div>

  <footer class="text-muted">
    <div class="container text-center">
      <p>Have a happy {% now "Y" %}</p>
      </div>
  </footer>

  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>